### ISSUE TITLE
Docs unclear that PaneResizer needs a slot to function

### ISSUE THREAD

**Issue by ghostdevv** [svecosystem/paneforge#10]
### Change Type

Addition

### Proposed Changes

I was confused about why it wasn't working for me, but I discovered that in order for the draggable area to show up you need an element in the `PaneResizer` component. It wasn't clear from my quick docs readthrough that I needed this until I looked in the code examples in the repo.

**Comment by huntabyte** [comment]
It doesn't need a slot to function. You just need to give it a height or width depending on the direction.

**Comment by huntabyte** [comment]
After trying to confirm I'm not going crazy I confirmed I am going crazy. At the moment you do need a slot but I want to say this is a bug and you _shouldn't_ need one.

**Comment by huntabyte** [comment]
Alright, was able to confirm a slot is _not_ needed.

Here's an example (with tailwind styles) of it working without a slot:

```svelte
<script lang="ts">
	import { PaneGroup, Pane, PaneResizer } from "paneforge";
</script>

<PaneGroup direction="horizontal" class="w-full rounded-lg">
	<Pane defaultSize={50} class="bg-gray-800 rounded-lg">
		<div class="flex h-[400px] items-center justify-center p-6">
			<span class="font-semibold">Left</span>
		</div>
	</Pane>
	<PaneResizer class="bg-black min-h-full w-2" />
	<Pane defaultSize={50} class="bg-gray-800 rounded-lg">
		<div class="flex h-full items-center justify-center p-6">
			<span class="font-semibold">Right</span>
		</div>
	</Pane>
</PaneGroup>
```

**Comment by ghostdevv** [comment]
I'd assume the reason you don't need a slot is because of those styles, so I think it still makes sense to update the docs with them
