### ISSUE TITLE
[Safari] ResizeHandle causing unexpected selection

### ISSUE THREAD

**Issue by fabi-flex** [svecosystem/paneforge#16]
### Describe the bug

Risizing a pane group using safari results in random selection flicker in some panes.

<img width="400" alt="Bildschirmfoto 2024-04-02 um 21 19 48" src="https://github.com/svecosystem/paneforge/assets/127057963/60806c85-e005-4ea4-aa72-f66bd0dd5140">

### Reproduction

Open the docs in safari and resize a pane

### System Info

```bash
Mac OS 14.4.1 with M1, Safari 17.4.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
I think user select may be causing this issue. I'll take a look to see if adding that property resolves the issue.

**Comment by huntabyte** [comment]
May have time to look into this this week/end but if anyone wants to take a look in the meantime, I'll gladly accept a PR for a fix!
