### ISSUE TITLE
Possible to add a `data-pane-collapsed` attribute?

### ISSUE THREAD

**Issue by nooblyf** [svecosystem/paneforge#32]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Because it is very complex to do collapsed size in pixels from what i see from the previous issues, I am trying to set the max height/width of a collapsed pane.

I know it's possible to do this with a state and using the pane API, but it would be really handy to have a data attribute giving out this information because then we'll be able to do it just like this

```text
data-[pane-collapsed]:max-w-[48px]

data-[pane-expanded]:max-w-none
```

### What type of pull request would this be?

Enhancement

**Comment by huntabyte** [comment]
This is a good idea!

**Comment by huntabyte** [comment]
Added in `paneforge@next`
