### ISSUE TITLE
Add possibility for static elements

### ISSUE THREAD

**Issue by GideonKoenig** [svecosystem/paneforge#40]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Currently, when you add elements within a PaneGroup that are not Pane components, the handle drifts while resizing.

**Example:**
```svelte
<Resizable.PaneGroup>
    <div> Element of a fixed size </div> 
    <Resizable.Pane />
    <Resizable.Handle />
    <Resizable.Pane />
</Resizable.PaneGroup>
```

**Attempted Workaround:**
I tried adding a "collapsed" element with a dummy handle as a workaround, but as you can only define the size of Panes as a percentage of the total available space, resizing the PaneGroup itself lead to unwanted resizing of the "static" element.

**Desired Solution:**
Having either another component, or a prop to define a static Pane or a way of defining the size of a collapsed Pane in px or rem would solve this.

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
I'm not sure this would make sense/be possible. We can't know how much space that random `div` is taking up in order to compute the remaining amounts.
