### ISSUE TITLE
The pane collapse size is supposed to be the collapsed size in px and not percentage

### ISSUE THREAD

**Issue by shal1y** [svecosystem/paneforge#42]
### Describe the bug

The pane collapses into percentage of the group size and not into the size of pixels as stated in the docs. If this is expected behaviour, then maybe update the docs :) or else this is weird. 

### Reproduction

Make the Pane group and add two panes with one being able to collapse, and set the collapsedSize (supposed to be number and not percent).
Use the api to collapse the pane.
The pane collapses into percent and not actual size.

### System Info

```bash
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 905.91 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
    bun: 1.1.24 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 128.1.69.162
    Safari: 17.6
  npmPackages:
    @sveltejs/kit: ^2.5.18 => 2.5.18 
    paneforge: ^0.0.5 => 0.0.5 
    svelte: ^4.2.18 => 4.2.18
```

### Severity

annoyance

**Comment by huntabyte** [comment]
Can you provide where in the docs it states pixels?

**Comment by shal1y** [comment]
It does not! but all other places it specifies the dimensions to be in %age when they are. Here it just says the size of (not %age size of). I assumed that it would be diff. 
Here, take a look:

```ts
export type PaneProps = {
    /**
     * The size of the pane when it is in a collapsed state.
     */
    collapsedSize?: number;
  
    /**
     * The default size of the pane in percentage.
     */
    defaultSize?: number;
  
    /**
     * The maximum size of the pane in percentage of the group's size.
     *
     * @defaultValue `100`
     */
    maxSize?: number;
    /**
     * The minimum size of the pane in percentage of the group's size.
     *
     * @defaultValue `0`
     */
    minSize?: number;
```

See what I mean?

**Comment by huntabyte** [comment]
If everywhere else says percentage, why would this one specific thing be pixels? Will update the JSDoc comments to be more explicit when I get the chance!

**Comment by shal1y** [comment]
Love all your components man, I was looking for this "particular" solution, and when I saw that only the `collapsedSize` was not in %age, I thought otherwise. Anyways, thanks for taking the time.
