### ISSUE TITLE
Default size with pixel value

### ISSUE THREAD

**Issue by StevenStavrakis** [svecosystem/paneforge#51]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Sometimes it is more useful to have a pane start at a static size that doesn't respond to resizing of the entire PaneGroup. The ability to pass a string into `defaultSize` instead of an integer would allow devs to specify what units they want instead of defaulting to percent.

### What type of pull request would this be?

New Feature

**Comment by huntabyte** [comment]
It won't be added to this project anytime soon, see this issue for more information: https://github.com/svecosystem/paneforge/issues/11#issuecomment-1972459792
