### ISSUE TITLE
next: pane not bindable (PaneAPI)

### ISSUE THREAD

**Issue by syedkhairi** [svecosystem/paneforge#52]
### Describe the bug

Pane is not bindable error and breaks everything.

`Cannot use 'bind:' with this property. It is declared as non-bindable inside the component.
To mark a property as bindable: 'let { pane = $bindable() } = $props()'`

```
A component is attempting to bind to a non-bindable property `pane` belonging to node_modules/paneforge/dist/components/pane.svelte (i.e. `<wrapper bind:pane={...}>`). To mark a property as bindable: `let { pane = $bindable() } = $props()`
```

Running the same code in example [here](https://github.com/svecosystem/paneforge/blob/main/sites/docs/content/examples/collapsible-panes.md), breaks.

### Reproduction

[https://stackblitz.com/edit/bolt-sveltekit-chqvxd?file=src%2Froutes%2Fpaneforge%2F%2Bpage.svelte](https://stackblitz.com/edit/bolt-sveltekit-chqvxd?file=src%2Froutes%2Fpaneforge%2F%2Bpage.svelte)

### System Info

```bash
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1
    Memory: 1.30 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - /opt/homebrew/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.92
    Edge: 129.0.2792.89
    Safari: 18.1
  npmPackages:
    @sveltejs/kit: ^2.7.2 => 2.7.2 
    paneforge: ^1.0.0-next.1 => 1.0.0-next.1 
    svelte: ^5.0.3 => 5.0.3
```

### Severity

blocking all usage of PaneForge

**Comment by huntabyte** [comment]
You now just need to `bind:this` and the type of the `typeof Pane`. Here's a link to the `next` docs: https://ae6e230f.paneforge.pages.dev/docs

I'll get the subdomain setup so it is `next.paneforge.com` soon.

**Comment by noahstreller** [comment]
> You now just need to `bind:this` and the type of the `typeof Pane`. Here's a link to the `next` docs: [ae6e230f.paneforge.pages.dev/docs](https://ae6e230f.paneforge.pages.dev/docs)
> 
> I'll get the subdomain setup so it is `next.paneforge.com` soon.

Could you please provide a minimal example? I can't find the updated code in the page you provided.

On this page it still uses the same code as on the regular docs: https://ae6e230f.paneforge.pages.dev/docs/examples/collapsible-panes
