### ISSUE TITLE
Hiding and unhiding a pane causes increases width. Paneforge version = 	"1.0.0-next.1"

### ISSUE THREAD

**Issue by razein97** [svecosystem/paneforge#54]
### Describe the bug

When hiding and unhiding a pane using the the if statement in sveltekit, it causes the width to keep on increasing on every subsequent show.
This bug is present in the paneforge and shadcn-svelte 5 version.

https://github.com/user-attachments/assets/c9622c7c-fa8e-474e-9d56-28ccfc1da8cc

### Reproduction

- Add a pane group and add two panes in it.

https://stackblitz.com/edit/sveltejs-kit-template-default-acvruj?file=src%2Froutes%2F%2Blayout.svelte

### System Info

```bash
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 68.56 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.12.1 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Brave Browser: 131.1.73.89
    Safari: 18.1.1
  npmPackages:
    @sveltejs/kit: 2.8.3 => 2.8.3 
    paneforge: 1.0.0-next.1 => 1.0.0-next.1 
    svelte: 5.2.7 => 5.2.7
```

### Severity

blocking all usage of PaneForge

**Comment by reinhard-sanz** [comment]
Same issue here, it also screws up the resizeability of the panes and behaves very weird. 
Works fine on `0.0.6` though.
